Name:Srujan Nalawade

PRN:25070123140

Batch: ENTC-A1

#Experiment-8
#Tools for EDA-Numpy(UNIT-2)

In [3]:
import numpy as np

a = np.array(([10,20,30,40]))
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [4]:
b.ndim

2

In [7]:
a.shape


(2, 3)

In [8]:
b.shape

(2, 3)

In [9]:
a.dtype

dtype('int64')

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [17]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
a+5

array([15, 25, 35, 45])

In [21]:
a*2

array([20, 40, 60, 80])

In [24]:
np.mean(a)

np.float64(25.0)

In [25]:
np.max(a)

np.int64(40)

In [28]:
np.median(a)

np.float64(25.0)

In [29]:
np.min(a)

np.int64(10)

In [30]:
np.sum(a)

np.int64(100)